[package]
name = "git_dag_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
clap = { version = "4.5.19", features = ["derive"] }
git2 = "0.19.0"
anyhow = "1.0.89"

[profile.release]
debug = true